version: '3'
services:

    postgres:
        container_name: matcha_db
        image: postgres
        env_file:
            - .env
        volumes:
            - ./volumes/postgres:/var/lib/postgresql/data
        ports:
            - "5432"
        networks:
            - matcha_network

    matcha:
        container_name: matcha_app
        build:
            context: matcha_app
        env_file:
            - .env
        volumes:
            - ./volumes/matcha_logs:/var/log/matcha
        ports:
            - "8080:80"
        networks:
            - matcha_network

networks:
    matcha_network:
